stages:
  - build
  - test
  - deploy

before_scripts:
  image: node:lts

build job:
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build/
      - node_modules


test job:
  stage: test
  script:
    - yarn test