stages:
  - build
  - test
  - deploy

build job:
  stage: build
  image: node:lts
  script:
    - yarn build
  artifacts:
    paths:
      - build/


test job:
  image: node:lts
  stage: test
  script:
    - yarn test